### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by axsddlr** [picklejason/ValorantRankedPointsBot#5]
```
Traceback (most recent call last):
  File "bot.py", line 215, in profile
    embed = await create_embed(user.id)
  File "bot.py", line 271, in create_embed
    stats, rank_num, rank, RP, ELO, _ = await process_stats(discord_id, 3)
  File "bot.py", line 260, in process_stats
    after, diff, rank_nums, maps, arrows, start_times, curr_matches = await rs.get_stats(player_id, headers, num_matches)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by picklejason** [comment]
That just means the user doesn't exist in your database / it can't access it. Is your fork up to date? I've fixed a couple of bugs for yesterday that may solve most of these issues. If possible message me on discord @PickleJason#5293 as I can reply there faster.

**Comment by axsddlr** [comment]
@picklejason tried to add on discord but it didnt work, however, the issue still persists on both windows and linux
